[package]
name = "diff-test-hotshot"
description = "Helpers and mocks for Forge-powered differential tests on HotShot-related contracts"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
ark-bn254 = { workspace = true }
ark-ec = { workspace = true }
ark-ed-on-bn254 = { workspace = true }
ark-ff = { workspace = true }
ark-poly = { workspace = true }
ark-std = { workspace = true }
clap = { version = "^4.4", features = ["derive"] }
diff-test-bn254 = { git = "https://github.com/EspressoSystems/solidity-bn254.git" }
ethers = { version = "2.0.4" }
hotshot-contract-adapter = { path = "../adapter" }
hotshot-state-prover = { path = "../../../hotshot-state-prover" }
itertools = { workspace = true }
jf-pcs = { workspace = true }
jf-plonk = { workspace = true }
jf-signature = { workspace = true }
jf-utils = { workspace = true }
sha3 = { version = "0.10.8", default-features = false }

[[bin]]
name = "diff-test"
path = "src/main.rs"
