[files]
extend-exclude = [
  "data/initial_stake_table.toml",
  ".env",
  "*.json",
  "**/*.pdf",
  "doc/*.svg",
  "doc/*.puml",
  "**/*.drawio",
  "contracts/lib",
  "contract-bindings-alloy",
  "contract-bindings-ethers",
  "node-metrics/src/api/node_validator/v0/example_prometheus_metrics_output.txt",
  "hotshot-orchestrator/run-config.toml",
  "hotshot-macros/src/lib.rs"
]
