version: "1"
services:
  cdn-server:
    image: ghcr.io/espressosystems/espresso-sequencer/cdn-server:main
    ports:
      - "$ESPRESSO_CDN_SERVER_PORT:$ESPRESSO_CDN_SERVER_PORT"
    environment:
      - ESPRESSO_CDN_SERVER_PORT
      - ESPRESSO_CDN_SERVER_NUM_NODES=5
      - ESPRESSO_CDN_SERVER_START_DELAY=5s
      - RUST_LOG

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      # Run the API server and the commitment task (with options taken from the environment)
      - ESPRESSO_SEQUENCER_API=""
      - ESPRESSO_SEQUENCER_COMMITMENT_TASK=""

      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
    healthcheck:
      test: curl --fail http://localhost:$ESPRESSO_SEQUENCER_API_PORT  || exit 1
      interval: 5s
      retries: 5
      timeout: 20s
  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER1_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      # Run the API server (with options taken from the environment)
      - ESPRESSO_SEQUENCER_API=""
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER2_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      # Run the API server (with options taken from the environment)
      - ESPRESSO_SEQUENCER_API=""
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER3_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      # Run the API server (with options taken from the environment)
      - ESPRESSO_SEQUENCER_API=""
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server
  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER4_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    environment:
      # Run the API server (with options taken from the environment)
      - ESPRESSO_SEQUENCER_API=""
      - ESPRESSO_SEQUENCER_CDN_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      - cdn-server

  demo-l1-network:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - $ESPRESSO_SEQUENCER_L1_PORT:8545
    # The way the foundry image handles arguments is strange, the double quotes
    # make it work here.
    command: "'anvil --host 0.0.0.0 --chain-id 1337'"
  example-rollup:
    image: ghcr.io/espressosystems/espresso-sequencer/example-rollup:main
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_DEMO_L1_PROVIDER
      - ESPRESSO_DEMO_ROLLUP_ADDRESS
      - ESPRESSO_DEMO_HOTSHOT_ADDRESS
      - ESPRESSO_DEMO_ROLLUP_PORT
      - ESPRESSO_DEMO_ROLLUP_MNEMONIC
    ports:
      - "$ESPRESSO_DEMO_ROLLUP_PORT:$ESPRESSO_DEMO_ROLLUP_PORT"
    depends_on:
      sequencer0:
        condition: service_healthy
