version: "1"
services:
  orchestrator:
    image: ghcr.io/espressosystems/espresso-sequencer/orchestrator:main
    ports:
      - "$ESPRESSO_ORCHESTRATOR_PORT:$ESPRESSO_ORCHESTRATOR_PORT"
    environment:
      - ESPRESSO_ORCHESTRATOR_PORT
      - ESPRESSO_ORCHESTRATOR_NUM_NODES=5
      - ESPRESSO_ORCHESTRATOR_START_DELAY=5s
      - RUST_LOG

  da-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_DA_SERVER_PORT:$ESPRESSO_DA_SERVER_PORT"
    environment:
      - ESPRESSO_DA_SERVER_PORT
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy

  consensus-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_WEB_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment) and the optional submission API
    command: sequencer -- http -- query -- submit
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy
  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER1_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy
  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER2_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy
  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER3_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy
  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER4_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - RUST_LOG
    depends_on:
      orchestrator:
        condition: service_healthy

  demo-l1-network:
    image: ghcr.io/foundry-rs/foundry:latest
    ports:
      - $ESPRESSO_SEQUENCER_L1_PORT:8545
    # The way the foundry image handles arguments is strange, the double quotes
    # make it work here.
    command: "'anvil --host 0.0.0.0 --chain-id 1337'"

  example-rollup:
    image: ghcr.io/espressosystems/espresso-sequencer/example-rollup:main
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_DEMO_L1_PROVIDER
      - ESPRESSO_DEMO_ROLLUP_ADDRESS
      - ESPRESSO_DEMO_HOTSHOT_ADDRESS
      - ESPRESSO_DEMO_ROLLUP_PORT
      - ESPRESSO_DEMO_ROLLUP_MNEMONIC
      - RUST_LOG
    ports:
      - "$ESPRESSO_DEMO_ROLLUP_PORT:$ESPRESSO_DEMO_ROLLUP_PORT"
    depends_on:
      sequencer0:
        condition: service_healthy
