version: "3"

networks:
  default:
    name: espresso-sequencer

services:
  demo-l1-network:
    image: ghcr.io/espressosystems/geth-l1:main
    ports:
      - $ESPRESSO_SEQUENCER_L1_PORT:8545
      - $ESPRESSO_SEQUENCER_L1_WS_PORT:8546
    volumes:
      - "./geth-config/genesis.json:/genesis.json"
      - "./geth-config/test-jwt-secret.txt:/config/test-jwt-secret.txt"

  orchestrator:
    image: ghcr.io/espressosystems/espresso-sequencer/orchestrator:main
    ports:
      - "$ESPRESSO_ORCHESTRATOR_PORT:$ESPRESSO_ORCHESTRATOR_PORT"
    environment:
      - ESPRESSO_ORCHESTRATOR_PORT
      - ESPRESSO_ORCHESTRATOR_NUM_NODES=5
      - ESPRESSO_ORCHESTRATOR_START_DELAY=5s
      - ESPRESSO_ORCHESTRATOR_NEXT_VIEW_TIMEOUT=30s
      - ESPRESSO_ORCHESTRATOR_MIN_TRANSACTIONS=1
      - ESPRESSO_ORCHESTRATOR_MIN_PROPOSE_TIME=0s
      - ESPRESSO_ORCHESTRATOR_MAX_PROPOSE_TIME=1s
      - RUST_LOG
      - RUST_LOG_FORMAT
    stop_grace_period: 1s

  da-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_DA_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  consensus-server:
    image: ghcr.io/espressosystems/espresso-sequencer/web-server:main
    ports:
      - "$ESPRESSO_CONSENSUS_SERVER_PORT:$ESPRESSO_WEB_SERVER_PORT"
    environment:
      - ESPRESSO_WEB_SERVER_PORT
      - RUST_LOG=error
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer0:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment) and the optional submission API
    command: sequencer -- http -- query -- submit
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer1:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER1_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer2:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER2_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer3:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER3_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http -- query
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  sequencer4:
    image: ghcr.io/espressosystems/espresso-sequencer/sequencer:main
    ports:
      - "$ESPRESSO_SEQUENCER4_API_PORT:$ESPRESSO_SEQUENCER_API_PORT"
    # Run the API server (with options taken from the environment)
    command: sequencer -- http
    environment:
      - ESPRESSO_SEQUENCER_ORCHESTRATOR_URL
      - ESPRESSO_SEQUENCER_DA_SERVER_URL
      - ESPRESSO_SEQUENCER_CONSENSUS_SERVER_URL
      - ESPRESSO_SEQUENCER_API_PORT
      - ESPRESSO_SEQUENCER_STORAGE_PATH
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      orchestrator:
        condition: service_healthy
    stop_grace_period: 1s

  commitment-task:
    image: ghcr.io/espressosystems/espresso-sequencer/commitment-task:main
    ports:
      - "$ESPRESSO_COMMITMENT_TASK_PORT:$ESPRESSO_COMMITMENT_TASK_PORT"
    command: commitment-task --deploy
    environment:
      - ESPRESSO_SEQUENCER_ETH_MNEMONIC
      - ESPRESSO_SEQUENCER_HOTSHOT_ACCOUNT_INDEX
      - ESPRESSO_COMMITMENT_TASK_PORT
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_SEQUENCER_L1_PROVIDER
      - ESPRESSO_SEQUENCER_L1_USE_LATEST_BLOCK_TAG
      - RUST_LOG
      - RUST_LOG_FORMAT
    depends_on:
      sequencer0:
        condition: service_healthy
      demo-l1-network:
        condition: service_healthy
    stop_grace_period: 1s

  example-rollup:
    image: ghcr.io/espressosystems/espresso-sequencer/example-rollup:main
    environment:
      - ESPRESSO_SEQUENCER_URL
      - ESPRESSO_DEMO_L1_HTTP_PROVIDER
      - ESPRESSO_DEMO_L1_WS_PROVIDER
      - ESPRESSO_DEMO_HOTSHOT_ADDRESS
      - ESPRESSO_DEMO_ROLLUP_PORT
      - ESPRESSO_DEMO_ROLLUP_MNEMONIC
      - ESPRESSO_DEMO_ROLLUP_ACCOUNT_INDEX
      - RUST_LOG
      - RUST_LOG_FORMAT
    ports:
      - "$ESPRESSO_DEMO_ROLLUP_PORT:$ESPRESSO_DEMO_ROLLUP_PORT"
    depends_on:
      sequencer0:
        condition: service_healthy
      commitment-task:
        condition: service_healthy
    stop_grace_period: 1s
