[profile.default]
# Note that if we want to move the `./contracts` directory into its own repo we
# need to move the foundry.toml and remove the `./contracts` prefix from the
# directories below.
src = 'contracts/src'
out = 'contracts/out'
test = 'contracts/test'
libs = ['contracts/lib']
script = "contracts/script"
broadcast = "contracts/broadcast"
cache_path = "contracts/cache"

# Version should match the solc installed via flake, otherwise the contract
# artifacts may differ slightly.
solc = "0.8.23"
# The bytecode hash is no longer deterministic and prevents us from generating
# deterministic bindings. The "none" setting prevents solc from appending the
# IPFS hash to the bytecode.
bytecode_hash = "none"
ffi = true
extra_output = ["storageLayout"]
fs_permissions = [{ access = "read-write", path = "./contracts/script/"}, { access = "read-write", path = "contracts/out"}]
ignored_warnings_from = ['contracts/lib']

# Without the optimizer we hit stack too deep errors.
optimizer = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[rpc_endpoints]
local = "http://localhost:8545"


[fmt]
line_length=100
bracket_spacing=true
wrap_comments=true

[profile.ci]
fuzz = { runs = 1000 }
invariant = { runs = 1000 }
verbosity = 1

[profile.quick]
fuzz = { runs = 10 }
invariant = { runs = 10 }
verbosity = 1
