version: "3"
services:

  zkevm-aggregator:
    image: ghcr.io/espressosystems/zkevm-node:hotshot-integration
    expose:
      - 50081
      - 9091 # needed if metrics enabled
    environment:
      - ZKEVM_NODE_STATEDB_USER=state_user
      - ZKEVM_NODE_STATEDB_PASSWORD=state_password
      - ZKEVM_NODE_STATEDB_NAME=state_db
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      # - ZKEVM_NODE_AGGREGATOR_VERIFYPROOFINTERVAL=10s # Defaults to 90s
      # - ZKEVM_NODE_AGGREGATOR_RETRYTIME=2s # Defaults to 5s
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_URL=http://zkevm-mock-l1-network:$ESPRESSO_ZKEVM_L1_PORT
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_ZKEVM_HOTSHOT_ADDRESS
      # Use the deployer account to match zkevm-contracts geth L1 deployment.
      - ZKEVM_NODE_AGGREGATOR_SENDERADDRESS=0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
    volumes:
      - ./zkevm-node/test/sequencer.keystore:/pk/sequencer.keystore
      - ./zkevm-node/test/aggregator.keystore:/pk/aggregator.keystore
      - ./zkevm-node/test/config/test.node.config.toml:/app/config.toml
      - ./zkevm-node/test/config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components aggregator"
    depends_on:
      - zkevm-permissionless-node

  zkevm-state-db:
    image: postgres
    deploy:
      resources:
        limits:
          memory: 1G
    expose:
      - 5432
    volumes:
      - ./zkevm-node/db/scripts/init_prover_db.sql:/docker-entrypoint-initdb.d/1.sql
      - ./zkevm-node-additions/init_pool_db.sql:/docker-entrypoint-initdb.d/2.sql
    environment:
      - POSTGRES_USER=state_user
      - POSTGRES_PASSWORD=state_password
      - POSTGRES_DB=state_db
    command: ["postgres", "-N", "500"]
    healthcheck:
      # Postgres can be falsely "ready" once before running init scripts.
      # See https://github.com/docker-library/postgres/issues/146 for discusson.
      test: "pg_isready -U state_user -d state_db && sleep 1 && pg_isready -U state_user -d state_db"
      interval: 1s
      timeout: 2s
      retries: 20

  zkevm-prover:
    image: hermeznetwork/zkevm-prover:88f3835
    expose:
      - 50052 # Mock prover
      - 50061 # MT
      - 50071 # Executor
    volumes:
      - ./zkevm-node/test/config/test.prover.config.json:/usr/src/app/config.json
    command: >
      zkProver -c /usr/src/app/config.json
    depends_on:
      - zkevm-permissionless-node
    stop_signal: SIGKILL

  zkevm-permissionless-node:
    image: ghcr.io/espressosystems/zkevm-node:hotshot-integration
    ports:
      - $ESPRESSO_ZKEVM_L2_PORT:$ESPRESSO_ZKEVM_L2_PORT
    environment:
      - ZKEVM_NODE_TRUSTED=false
      - ZKEVM_NODE_STATEDB_USER=state_user
      - ZKEVM_NODE_STATEDB_PASSWORD=state_password
      - ZKEVM_NODE_STATEDB_NAME=state_db
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_POOL_DB_USER=state_user
      - ZKEVM_NODE_POOL_DB_PASSWORD=state_password
      - ZKEVM_NODE_POOL_DB_NAME=pool_db # different DB name to run pool migrations
      - ZKEVM_NODE_POOL_DB_HOST=zkevm-state-db
      - ZKEVM_NODE_RPC_PORT=$ESPRESSO_ZKEVM_L2_PORT
      - ZKEVM_NODE_RPC_SEQUENCERNODEURI=$ESPRESSO_ZKEVM_ADAPTOR_RPC_URL
      - ZKEVM_NODE_ETHERMAN_URL=http://zkevm-mock-l1-network:$ESPRESSO_ZKEVM_L1_PORT
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_ZKEVM_HOTSHOT_ADDRESS
      - ZKEVM_NODE_SYNCHRONIZER_GENBLOCKNUMBER=$ESPRESSO_ZKEVM_GENBLOCKNUMBER
    volumes:
      - ./zkevm-node/test/sequencer.keystore:/pk/keystore
      - ./zkevm-node/test/config/test.node.config.toml:/app/config.toml
      - ./zkevm-node/test/config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components \"rpc,synchronizer\""
    depends_on:
      # This service does depend on `zkevm-mock-l1-network` but docker compose
      # v2.16.0 may decide to restart and recreate the `zkevm-mock-l1-network`
      # container after contract deployment, when we start the zkevm-node
      # services. This causes the state of the L1 to reset which makes the
      # deployed contracts disappear and breaks the zkevm-node.
      #
      # zkevm-mock-l1-network:
      #   condition: service_started
      zkevm-state-db:
        condition: service_healthy
    healthcheck:
      # curl not installed in container, but wget is
      test: "wget http://localhost:$ESPRESSO_ZKEVM_L2_PORT -q --spider --tries 1 || exit 1"
      interval: 0.5s
      timeout: 0.5s
      retries: 120
    extra_hosts:
      - "host.docker.internal:host-gateway"

  zkevm-eth-tx-manager:
    image: ghcr.io/espressosystems/zkevm-node:hotshot-integration
    environment:
      - ZKEVM_NODE_STATEDB_USER=state_user
      - ZKEVM_NODE_STATEDB_PASSWORD=state_password
      - ZKEVM_NODE_STATEDB_NAME=state_db
      - ZKEVM_NODE_STATEDB_HOST=zkevm-state-db
      - ZKEVM_NODE_ETHERMAN_POEADDR=$ESPRESSO_ZKEVM_ROLLUP_ADDRESS
      - ZKEVM_NODE_ETHERMAN_MATICADDR=$ESPRESSO_ZKEVM_MATIC_ADDRESS
      - ZKEVM_NODE_ETHERMAN_GLOBALEXITROOTMANAGERADDR=$ESPRESSO_ZKEVM_GER_ADDRESS
      - ZKEVM_NODE_ETHERMAN_URL=http://zkevm-mock-l1-network:$ESPRESSO_ZKEVM_L1_PORT
      - ZKEVM_NODE_ETHERMAN_HOTSHOTQUERYSERVICEURL=$ESPRESSO_ZKEVM_ADAPTOR_QUERY_URL
      - ZKEVM_NODE_ETHERMAN_HOTSHOTADDR=$ESPRESSO_ZKEVM_HOTSHOT_ADDRESS
    volumes:
      - ./zkevm-node/test/sequencer.keystore:/pk/sequencer.keystore
      - ./zkevm-node/test/aggregator.keystore:/pk/aggregator.keystore
      - ./zkevm-node/test/config/test.node.config.toml:/app/config.toml
      - ./zkevm-node/test/config/test.genesis.config.json:/app/genesis.json
    command:
      - "/bin/sh"
      - "-c"
      - "/app/zkevm-node run --genesis /app/genesis.json --cfg /app/config.toml --components eth-tx-manager"
    depends_on:
      zkevm-permissionless-node:
        condition: service_healthy
