[advisories]
ignore = [
    # remove_dir_all (used by deprecated tempdir crate)
    "RUSTSEC-2023-0018",
    # DoS in WebPKI that comes with tide_disco
    "RUSTSEC-2023-0052",
    # Tungstenite allows remote attackers to cause a denial of service
    # Dependency of async-tungstenite -> tide-websockets / surf-disco
    "RUSTSEC-2023-0065",
    # Unfixed "Marvin" vulnerability in `RSA`, unused in sqlite dependency
    "RUSTSEC-2023-0071",
    # rustls is busted, dependency of unmaintained tide
    "RUSTSEC-2024-0336",
    # sqlx is only used for CDN tests. No newer version available yet
    "RUSTSEC-2024-0363",
]
