[package]
name = "gen-vk-contract"
description = "Executable for generating SNARK verification key contract"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
ark-srs = { workspace = true }
hotshot-contract-adapter = { path = "../adapter" }
hotshot-stake-table = { workspace = true }
hotshot-state-prover = { path = "../../../hotshot-state-prover" }
jf-pcs = { workspace = true }
