[package]
name = "gen-vk-contract"
description = "Executable for generating SNARK verification key contract"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[dependencies]
ark-srs = { workspace = true }
clap = { workspace = true }
ethers = { version = "2.0.4" }
hotshot-contract-adapter = { workspace = true }
hotshot-stake-table = { workspace = true }
hotshot-state-prover = { workspace = true }
jf-pcs = { workspace = true }
workspace-hack = { version = "0.1", path = "../../../workspace-hack" }
