[package]
name = "sequencer-utils"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ark-serialize = { version = "0.3.0", features = ["derive"] }
async-std = { version = "1.12.0", features = ["attributes"] }
commit = { git = "https://github.com/EspressoSystems/commit", tag = "0.2.2" }
ethers = "2.0.3"
portpicker = "0.1.1"
surf = "2.3.2"
tracing = "0.1.37"
url = "2.3.1"
