[route.hotshot]
PATH = ["/hotshot"]
METHOD = "GET"
DOC = "Get the Hotshot configuration for the current node."

[route.env]
PATH = ["/env"]
METHOD = "GET"
DOC = "Get all ESPRESSO environment variables defined in public-env-vars.toml file for the current node"