[route.hotshot]
PATH = ["/hotshot"]
METHOD = "GET"
DOC = "Get the Hotshot configuration for the current node."

[route.env]
PATH = ["/env"]
METHOD = "GET"
DOC = "Get all ESPRESSO environment variables set for the current node."

[route.version]
PATH = ["/api_version"]
METHOD = "GET"
DOC = "Get the API version for the current node."

