# TOML file for the `/env` route of Config endpoint
# This file is used when the Config module is enabled.
# It specifies a list of environment variable names (`variables`) 
# that will be exposed by the `/env` route.


variables = [
    "ADDRESS",
    "AMOUNT",
    "BLOCK",
    "CONFIRMATIONS",
    "CONTRACT_ADDRESS",
    "ESPRESSO_CDN_BROKER_CA_CERT_PATH",
    "ESPRESSO_CDN_BROKER_DISCOVERY_ENDPOINT",
    "ESPRESSO_CDN_BROKER_METRICS_BIND_ENDPOINT",
    "ESPRESSO_CDN_BROKER_PUBLIC_ADVERTISE_ENDPOINT",
    "ESPRESSO_CDN_BROKER_PUBLIC_BIND_ENDPOINT",
    "ESPRESSO_CDN_MARSHAL_BIND_PORT",
    "ESPRESSO_CDN_MARSHAL_CA_CERT_PATH",
    "ESPRESSO_CDN_MARSHAL_DISCOVERY_ENDPOINT",
    "ESPRESSO_CDN_MARSHAL_METRICS_BIND_ENDPOINT",
    "ESPRESSO_CDN_WHITELIST_DISCOVERY_ENDPOINT",
    "ESPRESSO_COMMITMENT_TASK_DELAY",
    "ESPRESSO_COMMITMENT_TASK_PORT",
    "ESPRESSO_COMMITMENT_TASK_REQUEST_TIMEOUT",
    "ESPRESSO_DEPLOYER_OUT_PATH",
    "ESPRESSO_NASTY_CLIENT_HTTP_TIMEOUT_ERROR",
    "ESPRESSO_NASTY_CLIENT_HTTP_TIMEOUT_WARNING",
    "ESPRESSO_NASTY_CLIENT_MAX_BLOCKING_POLLS",
    "ESPRESSO_NASTY_CLIENT_MAX_OPEN_STREAMS",
    "ESPRESSO_NASTY_CLIENT_MAX_RETRIES",
    "ESPRESSO_NASTY_CLIENT_MIN_RETRIES",
    "ESPRESSO_NASTY_CLIENT_PORT",
    "ESPRESSO_NASTY_CLIENT_RETRY_DELAY",
    "ESPRESSO_NASTY_CLIENT_WEB_SOCKET_TIMEOUT",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_CLOSE_STREAM",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_OPEN_STREAM",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_POLL_STREAM",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_QUERY",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_QUERY_BLOCK_STATE",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_QUERY_FEE_STATE",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_QUERY_NAMESPACE",
    "ESPRESSO_NASTY_CLIENT_WEIGHT_QUERY_WINDOW",
    "ESPRESSO_ORCHESTRATOR_BUILDER_TIMEOUT",
    "ESPRESSO_ORCHESTRATOR_BUILDER_URLS",
    "ESPRESSO_ORCHESTRATOR_LIBP2P_MESH_N",
    "ESPRESSO_ORCHESTRATOR_NEXT_VIEW_TIMEOUT",
    "ESPRESSO_ORCHESTRATOR_NUM_NODES",
    "ESPRESSO_ORCHESTRATOR_PORT",
    "ESPRESSO_ORCHESTRATOR_ROUND_START_DELAY",
    "ESPRESSO_ORCHESTRATOR_START_DELAY",
    "ESPRESSO_ORCHESTRATOR_START_THRESHOLD",
    "ESPRESSO_ORCHESTRATOR_TIMEOUT_RATIO",
    "ESPRESSO_PROVIDER",
    "ESPRESSO_SEQUENCER_ACTIVE_FETCH_DELAY",
    "ESPRESSO_SEQUENCER_API_PEERS",
    "ESPRESSO_SEQUENCER_API_PORT",
    "ESPRESSO_SEQUENCER_ARCHIVE",
    "ESPRESSO_SEQUENCER_CATCHUP_BACKOFF_FACTOR",
    "ESPRESSO_SEQUENCER_CATCHUP_BACKOFF_JITTER",
    "ESPRESSO_SEQUENCER_CATCHUP_BASE_RETRY_DELAY",
    "ESPRESSO_SEQUENCER_CATCHUP_MAX_RETRY_DELAY",
    "ESPRESSO_SEQUENCER_CDN_ENDPOINT",
    "ESPRESSO_SEQUENCER_CHUNK_FETCH_DELAY",
    "ESPRESSO_SEQUENCER_FETCH_RATE_LIMIT",
    "ESPRESSO_SEQUENCER_HOTSHOT_ADDRESS",
    "ESPRESSO_SEQUENCER_HOTSHOT_EVENT_STREAMING_API_PORT",
    "ESPRESSO_SEQUENCER_IS_DA",
    "ESPRESSO_SEQUENCER_L1_EVENTS_MAX_BLOCK_RANGE",
    "ESPRESSO_SEQUENCER_LIBP2P_ADVERTISE_ADDRESS",
    "ESPRESSO_SEQUENCER_LIBP2P_BIND_ADDRESS",
    "ESPRESSO_SEQUENCER_MAX_CONNECTIONS",
    "ESPRESSO_SEQUENCER_ORCHESTRATOR_URL",
    "ESPRESSO_SEQUENCER_POSTGRES_DATABASE",
    "ESPRESSO_SEQUENCER_POSTGRES_HOST",
    "ESPRESSO_SEQUENCER_POSTGRES_PORT",
    "ESPRESSO_SEQUENCER_POSTGRES_PRUNE",
    "ESPRESSO_SEQUENCER_POSTGRES_USE_TLS",
    "ESPRESSO_SEQUENCER_POSTGRES_USER",
    "ESPRESSO_SEQUENCER_PRUNER_BATCH_SIZE",
    "ESPRESSO_SEQUENCER_PRUNER_INTERVAL",
    "ESPRESSO_SEQUENCER_PRUNER_MAX_USAGE",
    "ESPRESSO_SEQUENCER_PRUNER_MINIMUM_RETENTION",
    "ESPRESSO_SEQUENCER_PRUNER_PRUNING_THRESHOLD",
    "ESPRESSO_SEQUENCER_PRUNER_TARGET_RETENTION",
    "ESPRESSO_SEQUENCER_STAKE_TABLE_CAPACITY",
    "ESPRESSO_SEQUENCER_STATE_PEERS",
    "ESPRESSO_SEQUENCER_STORAGE_PATH",
    "ESPRESSO_SEQUENCER_STORE_UNDECIDED_STATE",
    "ESPRESSO_SEQUENCER_URL",
    "ESPRESSO_STATE_RELAY_SERVER_URL",
    "ESPRESSO_SUBMIT_TRANSACTIONS_CHANNEL_BOUND",
    "ESPRESSO_SUBMIT_TRANSACTIONS_DELAY",
    "ESPRESSO_SUBMIT_TRANSACTIONS_JOBS",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MAX_BATCH_SIZE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MAX_NAMESPACE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MAX_SIZE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MIN_BATCH_SIZE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MIN_NAMESPACE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_MIN_SIZE",
    "ESPRESSO_SUBMIT_TRANSACTIONS_PENDING_TRANSACTIONS_WARNING_THRESHOLD",
    "ESPRESSO_SUBMIT_TRANSACTIONS_PORT",
    "ESPRESSO_SUBMIT_TRANSACTIONS_SLOW_TRANSACTION_WARNING_THRESHOLD",
    "ESPRESSO_SUBMIT_TRANSACTIONS_SUBMIT_URL",
    "ESPRESSO_BENCH_START_BLOCK",
    "ESPRESSO_BENCH_END_BLOCK",
    "FROM",
    "TO"
]
