[package]
name = "hotshot_contract"
version = "0.1.0"
authors = ["Espresso Systems <hello@espressosys.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.71"
ark-bn254 = "0.4.0"
ark-ec = { version = "0.4.2" }
ark-ff = "0.4.2"
ark-serialize = "0.4.2"
ark-std = { version = "0.4.0", default-features = false }
async-compatibility-layer = { git = "https://github.com/EspressoSystems/async-compatibility-layer", tag = "1.30", features = [
    "logging-utils",
] }
async-std = "1.12.0"
contract-bindings = { path = "../../contract-bindings" }
digest = { version = "0.10", default-features = false, features = ["alloc"] }
ethers = { version = "2.0.4", features = ["abigen"] }
ethers-providers = "2.0.4"
ethers-solc = "2.0.4"
hex = "0.4.3"

# This crate requires a newer version than 0.1.2-patch.1 that's used elsewhere
# in this workspace. However not pinning any revision currently breaks
# dependency resolution.
jf-primitives = { git = "https://github.com/EspressoSystems/jellyfish", features = [
    "std",
] }
jf-utils = { git = "https://github.com/EspressoSystems/jellyfish", rev = "483fb97324d42724720f9155f200973a3b83a7b4" }
sequencer-utils = { path = "../../utils" }
sha3 = { version = "0.10.8", default-features = false }
