[route.submit]
PATH = ["/submit"]
METHOD = "POST"
DOC = "Submit transaction to the Example Rollup."

[route.balance]
PATH = ["/balance/:address"]
":address" = "Literal"
METHOD = "GET"
DOC = "Get balance by address. The address must be a hex encoded Ethereum address."
