on:
  push:
  workflow_dispatch:

name: udeps

env:
  RUSTFLAGS: '--cfg async_executor_impl="async-std" --cfg async_channel_impl="async-std"'

jobs:
  check:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        id: toolchain

      # Set nightly as the default toolchain
      - run: rustup override set ${{steps.toolchain.outputs.name}}

      - uses: Swatinem/rust-cache@v2
      
      - name: Install capnproto
        uses: ./.github/actions/install-capnp

      - name: Run cargo-udeps
        uses: aig787/cargo-udeps-action@v1
        with:
          version: latest
          args: --all-targets
